pipeline {
    agent any

    parameters {
        string(name: 'build_version', defaultValue: 'V1.0', description: 'Build version to use for Docker image')
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        GITHUB_TOKEN = credentials('github')
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Ndeye-codou-toure/devops-demo-project.git',
                    credentialsId: 'github'
            }
        }

        stage('Build and Test') {
            steps {
                dir('demo-java-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Static Code Analysis') {
            steps {
                dir('demo-java-app') {
                    withSonarQubeEnv('sonarqube') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=spring-boot-demo -Dsonar.projectName=spring-boot-demo'
                    }
                }
            }
        }
	stage('Build and Push Docker Image') {
            steps {
                dir('demo-java-app') {
                    script {
                        sh "docker build -t ndeyecodou/demo-java-app:${params.build_version} ."
                    }
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        '''
                    }
                    script {
                        sh "docker push ndeyecodou/demo-java-app:${params.build_version}"
                    }
                }
            }
        }
        stage('Update Deployment Tag') {
            steps {
                script {
                    sh "sed -i 's|tag:.*|tag: ${params.build_version}|' helm/app/values.yaml"
                    sh """
                        git config user.email 'jenkins@ci.com'
                        git config user.name 'Jenkins CI'
                        git add helm/app/values.yaml
                        git commit -m 'Update deployment image to version ${params.build_version}'
                        git push https://${GITHUB_TOKEN}@github.com/Ndeye-codou-toure/devops-demo-project.git main
                    """
                }
            }
        }
    }
}
